// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqlzafBrO_GCVCWY4A51a07k10eRv9iiI',
    appId: '1:17900353059:web:5977f5a93ec61f05066396',
    messagingSenderId: '17900353059',
    projectId: 'travelhub-74640',
    authDomain: 'travelhub-74640.firebaseapp.com',
    storageBucket: 'travelhub-74640.appspot.com',
    measurementId: 'G-GCS8TKR90R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvahWs0s32VmQWGFaHSMrKuyyXjmxg9_E',
    appId: '1:17900353059:android:d00e7130558cc557066396',
    messagingSenderId: '17900353059',
    projectId: 'travelhub-74640',
    storageBucket: 'travelhub-74640.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYz1eYFP3ge-VmQPigUWac3Q6n7MTQRj0',
    appId: '1:17900353059:ios:68a637a03a4517ca066396',
    messagingSenderId: '17900353059',
    projectId: 'travelhub-74640',
    storageBucket: 'travelhub-74640.appspot.com',
    androidClientId: '17900353059-pbdrg1lmtrmpc8147sotsdt9tn8erji6.apps.googleusercontent.com',
    iosClientId: '17900353059-jqco2g0jcjuos5jeh3sf0qqdadg196jd.apps.googleusercontent.com',
    iosBundleId: 'com.khaterCS.travelhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYz1eYFP3ge-VmQPigUWac3Q6n7MTQRj0',
    appId: '1:17900353059:ios:221816e4a3e05aec066396',
    messagingSenderId: '17900353059',
    projectId: 'travelhub-74640',
    storageBucket: 'travelhub-74640.appspot.com',
    androidClientId: '17900353059-pbdrg1lmtrmpc8147sotsdt9tn8erji6.apps.googleusercontent.com',
    iosClientId: '17900353059-77eb81snv5u86vi6gq1enlo4563v53ka.apps.googleusercontent.com',
    iosBundleId: 'com.khaterCS.travelhub.RunnerTests',
  );
}
