// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqlzafBrO_GCVCWY4A51a07k10eRv9iiI',
    appId: '1:17900353059:web:8c5e7e207e3f3ef6066396',
    messagingSenderId: '17900353059',
    projectId: 'travelhub-74640',
    authDomain: 'travelhub-74640.firebaseapp.com',
    storageBucket: 'travelhub-74640.appspot.com',
    measurementId: 'G-83KQEHJZ7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvahWs0s32VmQWGFaHSMrKuyyXjmxg9_E',
    appId: '1:17900353059:android:78cb02eb51b5ae82066396',
    messagingSenderId: '17900353059',
    projectId: 'travelhub-74640',
    storageBucket: 'travelhub-74640.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYz1eYFP3ge-VmQPigUWac3Q6n7MTQRj0',
    appId: '1:17900353059:ios:1b9d4ba94aa07e30066396',
    messagingSenderId: '17900353059',
    projectId: 'travelhub-74640',
    storageBucket: 'travelhub-74640.appspot.com',
    iosClientId: '17900353059-qovcc7rijqnf88n03bg58b7olmkn1h30.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYz1eYFP3ge-VmQPigUWac3Q6n7MTQRj0',
    appId: '1:17900353059:ios:3a745a0827522afd066396',
    messagingSenderId: '17900353059',
    projectId: 'travelhub-74640',
    storageBucket: 'travelhub-74640.appspot.com',
    iosClientId: '17900353059-auoakkuhp95u0jk7pglte52223gle8e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelhub.RunnerTests',
  );
}
